import 'package:flutter/material.dart';

import 'package:meals_app/models/category.dart';

import 'models/meal.dart';

const DUMMY_CATEGORIES = [
  Category(id: 'c1', title: 'Italian', color: Colors.purple),
  Category(id: 'c2', title: 'Quick & Easy', color: Colors.red),
  Category(id: 'c3', title: 'Hamburgers', color: Colors.orange),
  Category(id: 'c4', title: 'German', color: Colors.amber),
  Category(id: 'c5', title: 'Light & Lovely', color: Colors.blue),
  Category(id: 'c6', title: 'Exotic', color: Colors.green),
  Category(id: 'c7', title: 'Breakfast', color: Colors.lightBlue),
  Category(id: 'c8', title: 'Asian', color: Colors.lightGreen),
  Category(id: 'c9', title: 'French', color: Colors.pink),
  Category(id: 'c10', title: 'Summer', color: Colors.teal),
];

const DUMMY_MEALS = [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 20,
    ingredients: [
      'Tomato Sauce',
      'Spaghetti',
      'Onions',
      'Garlic',
      'Olive Oil',
      'Salt',
    ],
    steps: [
      'Cook pasta in a large pot of lightly salted water until al dente.',
      'Heat oil in a large skillet over medium heat. Add garlic and cook until fragrant, about 30 seconds. Add onion and cook until translucent, about 5 minutes.',
      'Stir in tomato sauce, season with salt, and simmer until flavors are blended, about 5 minutes.',
      'Toss pasta with sauce.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.pricey,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 10,
    ingredients: [
      'Butter',
      'Honey',
      'Ham',
      'Pineapple',
      'Bread',
    ],
    steps: [
      'Butter one side of each slice of bread.',
      'Place the bread, butter side down, onto a hot griddle or frying pan.',
      'Layer ham and pineapple on 4 slices of the bread; top with the remaining 4 slices, butter side up.',
      'Cook until golden brown on both sides.',
      'Spread honey over the cooked side of the bread.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c3',
      'c2',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.pricey,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 45,
    ingredients: [
      '300g Cattleman\'s Grill® Ground Beef',
      '1/2 cup Ketchup',
      '1/4 cup Yellow Mustard',
      '1 tbsp. Worcestershire Sauce',
      '1 tbsp. Dijon Mustard',
      '1 tbsp. Brown Sugar',
      '1 tbsp. Onion Powder',
      '1 tbsp. Garlic Powder',
      '1 tbsp. Paprika',
      '1 tbsp. Salt',
      '1 tbsp. Black Pepper',
      '4 Hamburger Buns',
      '4 Slices American Cheese',
      '4 Slices Bacon',
      '4 Lettuce Leaves',
      '4 Tomato Slices',
      '4 Onion Slices',
    ],
    steps: [
      'In a large bowl, combine ground beef, ketchup, yellow mustard, Worcestershire sauce, Dijon mustard, brown sugar, onion powder, garlic powder, paprika, salt, and pepper.',
      'Mix until well combined.',
      'Form into 4 patties.',
      'Grill over medium heat for 4-5 minutes per side, or until cooked through.',
      'Top each patty with 1 slice of cheese and 1 slice of bacon.',
      'Continue grilling until cheese is melted.',
      'Serve on buns with lettuce, tomato, and onion.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.luxurious,
    complexity: Complexity.challenging,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 60,
    ingredients: [
      '8 veal cutlets',
      '4 eggs',
      '200g bread crumbs',
      '100g flour',
      '300ml vegetable oil',
      'salt',
      'lemon slices',
      'parsley sprigs',
    ],
    steps: [
      'Tenderize the veal if needed.',
      'Season with salt and pepper.',
      'Dredge in flour, then dip in egg, and finally coat in bread crumbs.',
      'Heat oil in a large pan over medium-high heat.',
      'Fry the veal cutlets for 2-3 minutes on each side, or until golden brown.',
      'Drain on paper towels.',
      'Serve with lemon wedges and parsley.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.luxurious,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lemon',
      'Olive Oil',
      'Salt',
      'Pepper',
      'Smoked Salmon',
      'Hard Boiled Eggs',
      'Avocado',
      'Dill',
    ],
    steps: [
      'Wash and dry arugula.',
      'Zest lemon and set aside.',
      'Juice lemon and set aside.',
      'In a small bowl, whisk together lemon juice, olive oil, salt, and pepper.',
      'In a large bowl, toss arugula with lemon vinaigrette.',
      'Divide arugula among 4 plates.',
      'Top each salad with smoked salmon, hard boiled eggs, avocado, and dill.',
      'Serve immediately.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.luxurious,
    complexity: Complexity.hard,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatin',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatin in orange juice.',
      'Stir in sugar until dissolved.',
      'Let cool slightly, then stir in yoghurt.',
      'Whip cream until stiff peaks form.',
      'Fold into orange mixture.',
      'Pour into glasses and chill for at least 2 hours.',
      'Garnish with orange peel and serve.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.affordable,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 20,
    ingredients: [
      '1 cup all-purpose flour',
      '3 tablespoons white sugar',
      '1 teaspoon baking powder',
      '1 teaspoon salt',
      '1 egg',
      '1 1/4 cups milk',
      '3 tablespoons butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, sugar, baking powder and salt.',
      'Make a well in the center and pour in the egg, milk and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.',
      'Brown on both sides and serve hot.',
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.pricey,
    complexity: Complexity.challenging,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Natural Yogurt',
      '1 Teaspoon Garam Masala',
      '1 Teaspoon Paprika',
      '1 Teaspoon Cumin',
      '1 Teaspoon Coriander',
      '1 Teaspoon Cayenne Pepper',
      '1 Teaspoon Salt',
      '1 Cup Heavy Cream',
      '1 Tablespoon Cornstarch',
      '1 Tablespoon Water',
    ],
    steps: [
      'Cut chicken breasts into bite-sized pieces.',
      'Peel and finely chop onion.',
      'Peel and grate garlic and ginger.',
      'In a large bowl, mix together yogurt, garam masala, paprika, cumin, coriander, cayenne pepper, and salt.',
      'Add chicken and mix to coat.',
      'Cover and refrigerate for at least 1 hour.',
      'Heat oil in a large skillet over medium-high heat.',
      'Add onion and cook until soft and translucent, about 5 minutes.',
      'Add garlic and ginger and cook for 1 minute.',
      'Add chicken and cook until no longer pink, about 5 minutes.',
      'Stir in cream and bring to a simmer.',
      'In a small bowl, mix together cornstarch and water.',
      'Stir into chicken mixture and cook until thickened, about 2 minutes.',
      'Serve over rice.',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.luxurious,
    complexity: Complexity.simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 15,
    ingredients: [
      '1 Bunch Asparagus',
      '1 Bunch Cherry Tomatoes',
      '1 Shallot',
      '1 Lemon',
      '1 Tablespoon Olive Oil',
      '1 Tablespoon Balsamic Vinegar',
      'Salt',
      'Pepper',
    ],
    steps: [
      'Trim woody ends off asparagus and cut into 1 inch pieces.',
      'Halve cherry tomatoes.',
      'Peel and finely chop shallot.',
      'Zest lemon and set aside.',
      'Juice lemon and set aside.',
      'In a large bowl, toss asparagus, tomatoes, and shallot with lemon juice, olive oil, balsamic vinegar, salt, and pepper.',
      'Serve immediately.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.luxurious,
    complexity: Complexity.hard,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/15/Recipe_logo.jpeg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatin',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatin in orange juice.',
      'Stir in sugar until dissolved.',
      'Let cool slightly, then stir in yoghurt.',
      'Whip cream until stiff peaks form.',
      'Fold into orange mixture.',
      'Pour into glasses and chill for at least 2 hours.',
      'Garnish with orange peel and serve.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
];
